CC = g++
SRC = Assignment1.cpp Camera.cpp
LIBS = -L/comp/175/public_html/labs/lib -lGL -lGLU -lglut -lglui
EXEC = Assignment1

all:
	$(CC) $(SRC) -o $(EXEC) $(LIBS)  -I. -I/comp/175/public_html/labs/include/

clean:
	rm -rf $(EXEC) *~
